import { db } from "@/db/postgres";
import {
  transactionRepository as createTransactionRepository,
  TransactionRepositoryFactory
} from "@/db/repositories/transactionRepository";
import {
  InsertTransaction,
  SelectTransaction,
  insertTransactionSchema
} from "@/db/repositories/schemas/transactionSchema";
import { ZodError } from "zod";
import createNotificationUseCase, { CreateNotificationInput } from "@/usecases/notification/createNotificationUseCase";
// Assuming internalGetUserIdFromSession is the way to get current user for notification.
// This might be better passed in or handled by a higher-level service that orchestrates both.
import { internalGetUserIdFromSession } from "@/app/(admin)/notifications/actions"; // Temporary direct import

/**
 * Defines the input data structure for creating a new transaction.
 * It includes all necessary fields for a new transaction, such as description,
 * value, type, status, partner ID, date, and due date, while omitting
 * fields auto-generated by the database like 'id', 'createdAt', and 'updatedAt'.
 * This type is derived from the `InsertTransaction` schema.
 */
export type CreateTransactionInput = Omit<InsertTransaction, 'id' | 'createdAt' | 'updatedAt'>;

/**
 * @description Use case for creating a new transaction.
 * It validates the input data, persists the transaction using the repository,
 * and then fetches and returns the complete transaction object.
 *
 * @param {CreateTransactionInput} transactionData - The data for the new transaction.
 * @param {TransactionRepositoryFactory} [transactionRepoFactory=createTransactionRepository] - Optional factory for transaction repository.
 * @returns {Promise<SelectTransaction>} The created transaction.
 * @throws {ZodError} If input data validation fails.
 * @throws {Error} If there's an issue with the repository or other unexpected errors.
 */
export default async function createTransactionUseCase(
  transactionData: CreateTransactionInput,
  transactionRepoFactory: TransactionRepositoryFactory = createTransactionRepository
): Promise<SelectTransaction> {
  // 1. Validate input data
  // insertTransactionSchema already expects fields like description, value, type, status, partnerId, date, due_date
  // It omits id, createdAt, updatedAt by default.
  // We need to ensure our CreateTransactionInput matches what insertTransactionSchema can parse
  // to become a valid InsertTransaction.
  const parsedData = insertTransactionSchema.parse(transactionData);

  const transactionRepo = transactionRepoFactory(db);

  // 2. Persist the transaction
  const { id: newId } = await transactionRepo.insert(parsedData);

  // 3. Fetch the complete transaction object
  // It's good practice to fetch the entity after creation to get DB-generated fields (like createdAt, default values)
  // and to confirm successful insertion.
  const newTransaction = await transactionRepo.findById(newId);

  if (!newTransaction) {
    // This case should ideally not happen if insert was successful and ID is correct.
    // But it's good to handle it defensively.
    throw new Error("Failed to retrieve the created transaction after insertion.");
  }

  // 4. Attempt to create a notification (best effort)
  try {
    const currentUserId = await internalGetUserIdFromSession(); // Or determine target user differently
    if (currentUserId) {
      const notificationData: CreateNotificationInput = {
        userId: currentUserId, // Notify the user who created it (or specific admin)
        type: "new_transaction",
        message: `Nova transação "${newTransaction.description}" (${
          newTransaction.type === "E" ? "Entrada" : "Saída"
        }) no valor de ${newTransaction.value.toLocaleString("pt-BR", { style: "currency", currency: "BRL"})} foi criada.`,
        relatedEntityId: newTransaction.id,
        relatedEntityType: "transaction",
      };
      // Not awaiting this intentionally if it's not critical for the transaction flow
      createNotificationUseCase(notificationData).catch(error => {
        console.error("Failed to create notification for new transaction:", error);
        // Do not let notification failure fail the transaction creation
      });
    } else {
      console.warn("No user ID found to create notification for new transaction.");
    }
  } catch (error) {
    console.error(
      "Error during notification creation for new transaction:",
      error
    );
    // Do not re-throw; notification is secondary
  }

  return newTransaction;
}
