import { db } from "@/db/postgres";
import {
  transactionRepository as createTransactionRepository,
  TransactionRepositoryFactory
} from "@/db/repositories/transactionRepository";
import {
  InsertTransaction,
  SelectTransaction,
  insertTransactionSchema
} from "@/db/repositories/schemas/transactionSchema";
import { ZodError } from "zod";

/**
 * Input data type for creating a transaction.
 * Derived from the Zod schema, excluding fields auto-generated by the database.
 */
export type CreateTransactionInput = Omit<InsertTransaction, 'id' | 'createdAt' | 'updatedAt'>;

/**
 * @description Use case for creating a new transaction.
 * It validates the input data, persists the transaction using the repository,
 * and then fetches and returns the complete transaction object.
 *
 * @param {CreateTransactionInput} transactionData - The data for the new transaction.
 * @param {TransactionRepositoryFactory} [transactionRepoFactory=createTransactionRepository] - Optional factory for transaction repository.
 * @returns {Promise<SelectTransaction>} The created transaction.
 * @throws {ZodError} If input data validation fails.
 * @throws {Error} If there's an issue with the repository or other unexpected errors.
 */
export default async function createTransactionUseCase(
  transactionData: CreateTransactionInput,
  transactionRepoFactory: TransactionRepositoryFactory = createTransactionRepository
): Promise<SelectTransaction> {
  // 1. Validate input data
  // insertTransactionSchema already expects fields like description, value, type, status, partnerId, date, due_date
  // It omits id, createdAt, updatedAt by default.
  // We need to ensure our CreateTransactionInput matches what insertTransactionSchema can parse
  // to become a valid InsertTransaction.
  const parsedData = insertTransactionSchema.parse(transactionData);

  const transactionRepo = transactionRepoFactory(db);

  // 2. Persist the transaction
  const { id: newId } = await transactionRepo.insert(parsedData);

  // 3. Fetch the complete transaction object
  // It's good practice to fetch the entity after creation to get DB-generated fields (like createdAt, default values)
  // and to confirm successful insertion.
  const newTransaction = await transactionRepo.findById(newId);

  if (!newTransaction) {
    // This case should ideally not happen if insert was successful and ID is correct.
    // But it's good to handle it defensively.
    throw new Error("Failed to retrieve the created transaction after insertion.");
  }

  return newTransaction;
}
