import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod";
import { transactionTable } from "../../postgres/schema/transaction";

export const insertTransactionSchema = createInsertSchema(transactionTable, {
  // Assuming 'description' and 'value' might have specific validations here.
  // The original had min(1) for description and positive() for value.
  // createInsertSchema already infers types, but explicit overrides can be made.
  description: z.string().min(1, "Descrição é obrigatória."),
  value: z.coerce.number({invalid_type_error: "Valor deve ser um número."}).positive("Valor deve ser positivo."),
  type: z.enum(["E", "S"], {errorMap: () => ({message: "Tipo deve ser 'E' (Entrada) ou 'S' (Saída)."})}),
  partnerId: z.string().uuid("ID do Parceiro inválido."),
  date: z.coerce.date().optional(),
  due_date: z.coerce.date().optional(),
  // transactionId (self-reference) is optional by default if nullable in DB schema
}).omit({
  // id is auto-generated by DB or should be if not provided
  id: true, // Usually omitted for insert schemas if DB generates it
  createdAt: true,
  updatedAt: true,
});
export type InsertTransaction = z.infer<typeof insertTransactionSchema>;

export const selectTransactionSchema = createSelectSchema(transactionTable, {
  // Ensure numeric types are coerced correctly if they come as strings from DB sometimes
  value: z.coerce.number(),
  // partnerId, etc., will be inferred as string (uuid)
});
export type SelectTransaction = z.infer<typeof selectTransactionSchema>;

// Schema for transactions that include the partner's name
export const selectTransactionWithPartnerSchema = selectTransactionSchema.extend({
  partnerName: z.string().optional(), // Partner name might be null if partner is deleted or not found
});
export type SelectTransactionWithPartner = z.infer<typeof selectTransactionWithPartnerSchema>;
